package com.bikerental.servlet;

import com.bikerental.dao.UserDAO;
import com.bikerental.model.Customer;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.UUID;

@WebServlet("/register")
public class RegisterServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        // 1. Form eken ena wisthara allagannawa (ID eka naha dan)
        String name = request.getParameter("name");
        String email = request.getParameter("email");
        String password = request.getParameter("password");

        // 2. Meken lassanata auto ID ekak hadanawa (e.g., U-A7F9B wage)
        String autoGeneratedId = "U-" + UUID.randomUUID().toString().substring(0, 5).toUpperCase();

        // 3. Achchuwen aluth Customer kenekwa hadanawa
        Customer newUser = new Customer();
        newUser.setId(autoGeneratedId); // Ara auto hadapu ID eka methanata denawa
        newUser.setName(name);
        newUser.setEmail(email);
        newUser.setPasswordHash(password);

        // 4. DAO eka haraha users.txt pothata wisthara tika liyanawa
        UserDAO dao = new UserDAO();
        dao.registerUser(newUser, password);

        // 5. Save unata passe browser eke lassanata message ekak pennanawa
        response.setContentType("text/html");
        response.getWriter().println("<h2>Registration Successful! Welcome " + name + "</h2>");
        response.getWriter().println("<p>Oyage auto-generated ID eka: <b>" + autoGeneratedId + "</b></p>");
        response.getWriter().println("<br><a href='" + request.getContextPath() + "/views/user/login.jsp'>Go to Login</a>");
    }
}